//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG6212POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class stest
    {
        public string studID { get; set; }
        public int questID { get; set; }
        public string ansChosen { get; set; }
        public Nullable<int> ansMark { get; set; }
    
        public virtual question question { get; set; }
        public virtual student student { get; set; }
    }
}
